use IT;

DELETE FROM ACCESSORIES WHERE AccessoriesTypeId = 1 AND IndexId = 1;

DELETE FROM PRODUCT WHERE ProductTypeId = 1 AND IndexId = 1;

/* DELETE ALL FROM TABLE
 * */
DELETE FROM ACCESSORIES;

DELETE FROM PRODUCT;

DELETE FROM EMPLOYEE;
